
export const MOVING_RIGHT_START = 'BOY/MOVING_RIGHT_START';
export const MOVING_RIGHT_STOP = 'BOY/MOVING_RIGHT_STOP';
export const MOVING_LEFT_START = 'BOY/MOVING_LEFT_START';
export const MOVING_LEFT_STOP = 'BOY/MOVING_LEFT_STOP';
export const JUMPING_START = 'BOY/JUMPING_START';
export const JUMPING_STOP = 'BOY/JUMPING_STOP';
export const SLIDING_START = 'BOY/SLIDING_START';
export const SLIDING_STOP = 'BOY/SLIDING_STOP';
export const LEFT_GROUND = 'BOY/LEFT_GROUND';
export const COLLIDED_WITH_GROUND = 'BOY/COLLIDED_WITH_GROUND';
